### ISSUE TITLE
suppress unused fields in params message?

### ISSUE THREAD

**Issue by M1chaelM** [osrf/vrx#617]
Because of some challenges introduced by the way we use protobufs, it is difficult to create custom messages in VRX 2.0 and above. As a consequence, we rely heavily on the "params" message. A drawback is that this message is very noisy and `ros2 topic echo` commands produce output that is hard to read without instrumentation.

The situation would be much better if there were an easy way to suppress unused fields in the param message. For example, in the following entry from the `range_bearing` topic for the acoustic pinger, only 2 fields are really relevant:
```
- name: range
  value:
    type: 3
    bool_value: false
    integer_value: 0
    double_value: 21.468399037071904
    string_value: ''
    byte_array_value: []
    bool_array_value: []
    integer_array_value: []
    double_array_value: []
    string_array_value: []
```
If we could display only the name and double_value fields this message would be much more human-friendly. I'm creating this issue as a reminder to check what options might be available.
